"""Fitting the tag-confidence curve to observed extractions.

Pure: rows in, two constants out. No I/O, no clock, no config — the arming,
the gate and the smoothing are separate jobs and live elsewhere.
"""

from __future__ import annotations

import math

import pytest

from src.scoring.curve_fit import Observation, expected_tags, fit_curve

_DEFAULT_CAP = 5.0
_DEFAULT_SATURATION = 190.0


def _from(cap: float, saturation: float, lengths: list[int]) -> list[Observation]:
    """Observations generated by a known curve, to fit back to it."""
    return [
        Observation(event_id=f"e{c}", chars=c, tags=expected_tags(c, cap, saturation), source_type="s")
        for c in lengths
    ]


class TestFit:
    def test_it_recovers_the_curve_that_generated_the_data(self):
        """The property everything else rests on."""
        rows = _from(3.8, 127.0, [30, 45, 60, 90, 120, 150, 200, 250, 400, 600, 800, 1500])

        cap, saturation = fit_curve(rows)

        assert cap == pytest.approx(3.8, abs=0.15)
        assert saturation == pytest.approx(127.0, rel=0.10)

    def test_it_is_deterministic(self):
        """Two identical corpora must fit identically, or a past score stops
        being recomputable from stored data."""
        rows = _from(4.2, 200.0, [40, 60, 80, 110, 160, 220, 320, 450, 640, 900, 1300])

        assert fit_curve(rows) == fit_curve(rows)

    def test_row_order_does_not_change_the_fit(self):
        rows = _from(4.2, 200.0, [40, 60, 80, 110, 160, 220, 320, 450, 640, 900, 1300])

        assert fit_curve(rows) == fit_curve(list(reversed(rows)))

    def test_the_fitted_curve_is_monotonic_in_chars(self):
        """True by definition for any model whose only input is a length, so a
        fit violating it is wrong whatever its R². Asserted, not hoped for."""
        rows = _from(3.8, 127.0, [30, 45, 60, 90, 130, 190, 250, 400, 550, 800, 1200])

        cap, saturation = fit_curve(rows)

        values = [expected_tags(c, cap, saturation) for c in range(1, 2000, 25)]
        assert all(b >= a for a, b in zip(values, values[1:]))

    def test_one_extreme_row_does_not_drag_the_fit(self):
        """A 5,000-character event earning a single tag is a real possibility,
        and under plain least squares it has enormous leverage on `cap`."""
        rows = _from(3.8, 127.0, [30, 45, 60, 90, 120, 150, 200, 250, 400, 600, 800, 1500])
        clean_cap, _ = fit_curve(rows)

        rows.append(Observation(event_id="outlier", chars=5000, tags=1.0, source_type="s"))
        robust_cap, _ = fit_curve(rows)

        assert abs(robust_cap - clean_cap) < 0.5

    def test_too_few_rows_is_refused_rather_than_guessed(self):
        """Arming is a separate decision, but a fit over three points is not a
        fit and must not silently look like one."""
        with pytest.raises(ValueError, match="rows"):
            fit_curve(_from(3.8, 127.0, [50, 100, 200]))

    def test_rows_with_no_length_are_refused(self):
        with pytest.raises(ValueError, match="chars"):
            fit_curve([Observation(event_id="z", chars=0, tags=1.0, source_type="s")] * 30)


class TestExpectedTags:
    def test_it_rises_from_zero_toward_the_cap(self):
        assert expected_tags(0, 5.0, 190.0) == pytest.approx(0.0)
        assert expected_tags(100_000, 5.0, 190.0) == pytest.approx(5.0, abs=0.01)

    def test_it_matches_the_formula_the_scorer_uses(self):
        expected = _DEFAULT_CAP * (1 - math.exp(-250 / _DEFAULT_SATURATION))

        assert expected_tags(250, _DEFAULT_CAP, _DEFAULT_SATURATION) == pytest.approx(expected)


class TestAgainstTheMeasuredCorpus:
    """Pins the numbers the plan was argued from.

    Measured 2026-08-14 over 273 real rows: a least-squares sweep gave
    cap 3.80 / saturation 127, and this Huber fit gives 3.70 / 124 — close,
    because the corpus has no extreme leverage points yet. If that drifts, the
    plan's premise has changed and should be re-argued rather than re-tuned.
    """

    def test_a_corpus_shaped_like_the_real_one_fits_near_the_measured_values(self):
        # Real shape: median ~80 chars, most rows short, a long tail to ~1800.
        lengths = [36, 40, 45, 50, 55, 60, 65, 70, 75, 80, 80, 85, 90, 100, 110,
                   120, 140, 160, 200, 260, 340, 450, 600, 900, 1400, 1779]
        rows = [
            Observation(event_id=f"e{c}", chars=c, tags=expected_tags(c, 3.75, 125.0), source_type="s")
            for c in lengths
        ]

        cap, saturation = fit_curve(rows)

        assert cap == pytest.approx(3.75, abs=0.2)
        assert saturation == pytest.approx(125.0, rel=0.15)

    def test_the_shipped_constants_are_not_what_this_corpus_implies(self):
        """The reason the refit exists. If a corpus of this shape ever fits back
        to 5.0/190, the static curve was right after all and the plan is moot."""
        lengths = [36, 45, 60, 75, 80, 90, 110, 140, 200, 300, 500, 900, 1400]
        rows = [
            Observation(event_id=f"e{c}", chars=c, tags=expected_tags(c, 3.75, 125.0), source_type="s")
            for c in lengths
        ]

        cap, _ = fit_curve(rows)

        assert cap < 4.5
